### PR TITLE
Installation improvements

### LINKED ISSUE #431: Write slp parser in cython
To enhance the code optimizations, the SLP reader in `openage/convert/slp.py` should be written in cython. Currently, this is the bottleneck for the asset conversion.

And if that's too slow as well, we can think about using C++ for it...

### LINKED ISSUE #690: Normalize install prefixes in cmake
Please normalize the paths that are shown after the buildsystem configuration step:

observed:
```
   install prefix | /usr/local/../asdf/../test
py install prefix | /usr/lib/python-exec/python3.5/../../../lib64/python3.5/site-packages
```

expected:
```
   install prefix | /usr/test
py install prefix | /usr/lib64/python3.5/site-packages
```

### LINKED ISSUE #708: blacklist pythontex in the buildsystem
Pythontex is some kind of a python interpreter bundled with texlive. CMake finds it, but it's not suitable for what we are doing (obviously). We should blacklist it to get rid of clutter in the configure output. Also the "dropping invalid python interpreter" message (for the remaining possible cases) should not be a warning, but a normal message without modifiers.

<details>
<summary>Configure output</summary>
<pre>
[...]
Testing /usr/bin/python3
Testing /usr/bin/python3.6
Testing /usr/bin/python2.7
Testing /usr/bin/python3.6m
Testing /usr/share/texmf-dist/scripts/pythontex/pythontex.py
usage: pythontex.py [-h] [--version] [--encoding ENCODING]
                    [--error-exit-code {true,false}] [--runall [{true,false}]
                    | --rerun {never,modified,errors,warnings,always}]
                    [--hashdependencies [{true,false}]] [-j N] [-v]
                    [--interpreter INTERPRETER]
                    [--debug [<family>:<session>:<restart>] | --interactive
                    [<family>:<session>:<restart>]]
                    TEXNAME
pythontex.py: error: unrecognized arguments: -c
CMake Warning at buildsystem/modules/FindPython.cmake:149 (message):
  Dropping invalid python interpreter
  '/usr/share/texmf-dist/scripts/pythontex/pythontex.py'
Call Stack (most recent call first):
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:69 (include)
[...]
</pre>
</details>

### LINKED ISSUE #709: Install global game binary
Currently, we don't install a game binary to e.g. `/usr/bin/openage`.
The only thing that complicates this is that we launch it from python, and installing some hacky bash script sucks.
Gentoo solves this with [`python-exec`](https://wiki.gentoo.org/wiki/Project:Python/python-exec), but we have to provide something similar for other distros.

The easiest way will probably be to just install the `run.py` script or the cythonized `run` executable.

The problem that needs to be solved is how we install that binary to the "correct" path without `distutils`, as we use `CMake` instead of `distutils` for compiling and installing the code.

In a nutshell:

* [x] Extend the buildsystem to figure out the distutils-equivalent install path (we can already do that for the openage python module itself)
* [x] modify `make install` to install the `run.py` as openage launcher script

### PR DESCRIPTION
**Pull request by TheJJ**
* [X] normalize python prefix (fixes #690)
* [X] install game launcher (fixes #709)
* [X] blacklist `pythontex.py` (fixes #708)
* [X] cache locating python and python modules
* [X] ninja build system support
* [X] enable repo assets directory depending on `devmode`
* [X] union-mount all possible asset search paths (`/usr/share`, `/home`, `--assets`, ...)
* [X] modernized file reading
  * use `std::istream`, `std::getline` etc
* [x] filesystem abstraction c++ interface (#630)
  * [X] abstraction layer through python
  * [x] abstraction layer through c++ stdlib
  * [x] filelike support through python
    * [X] reading
    * [x] writing
  * [x] filelike support through c++ stdlib
    * [x] reading
    * [x] writing
  * [x] wrapping the C++ api for python
    * the c++ objects can be passed again to python
    * filesystemlike and filelike api must be wrapped in the other direction again
* [x] integrate `util::Path` all over the codebase
  * [x] reading QML files and watch root dir
  * [x] improve docx reading
  * [x] audio manager
  * [x] asset manager
    * texture loading
    * sound loading
* [x] generic `.call()` method for python objects
* [x] random fixes and improvements
* [x] integration of #718 because this pullrequests requires a reconversion anyways
* [x] visgrep interface cutter optimizations (faster by factor ~50)
* [x] slp parser optimizations (faster by factor ~40) (fixes #431)
* [x] virtual file reading for audio system
* [x] cvar default loading

works towards #691

### CODE REVIEW

File: libopenage/util/csv.h [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+		std::vector<std::string> lines = file_map->at(fname);
+
+		for (auto &line : lines) {
+			line_count += 1;
+
+			// create writable copy, for tokenisation
+			if (unlikely(strbuf.size() <= line.size())) {
+				strbuf.resize(line.size() + 1);
+			}
+			memcpy(strbuf.data(), line.c_str(), line.size() + 1);
```
Comment (Tomatower) [inline libopenage/util/csv.h]: Why memcpy here?

std::copy(line.c_str(), line.c_str()+line.size(), std::back_inserter(strbuf));

File: libopenage/util/csv.h [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+			// ignore comments and empty lines
+			if (line.empty() || line[0] == '#') {
+				continue;
+			}
+
+			// create writable copy, for tokenisation
+			if (unlikely(strbuf.size() <= line.size())) {
+				strbuf.resize(line.size() + 1);
+			}
+			memcpy(strbuf.data(), line.c_str(), line.size() + 1);
```
Comment (Tomatower) [inline libopenage/util/csv.h]: memcpy?

File: libopenage/util/csv.h [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+			line_count += 1;
+
+			// create writable copy, for tokenisation
+			if (unlikely(strbuf.size() <= line.size())) {
+				strbuf.resize(line.size() + 1);
+			}
+			memcpy(strbuf.data(), line.c_str(), line.size() + 1);
+
+			// use the line copy to fill the current line struct.
+			int error_column = current_line_data.fill(strbuf.data());
```
Comment (Tomatower) [inline libopenage/util/csv.h]: Actually - Why not give the line.data() directly into the fill() method?

File: libopenage/util/csv.h [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+			}
+
+			// create writable copy, for tokenisation
+			if (unlikely(strbuf.size() <= line.size())) {
+				strbuf.resize(line.size() + 1);
+			}
+			memcpy(strbuf.data(), line.c_str(), line.size() + 1);
+
+			// use the line copy to fill the current line struct.
+			int error_column = current_line_data.fill(strbuf.data());
```
Comment (Tomatower) [inline libopenage/util/csv.h]: same here - use line.data() or

File: libopenage/util/csv.h (hunk 3 above)
Comment (TheJJ) [inline libopenage/util/csv.h]: because the fill method will modify the data, and i think that line.c_str() is const.

**Comment by TheJJ** [comment]
I'll clean the whole csv reading up, it's really a mess...

File: libopenage/util/csv.h (hunk 3 above)
Comment (Tomatower) [inline libopenage/util/csv.h]: Why does the fill method modify the data? strbuf is rewritten for every line

Comment (TheJJ) [inline libopenage/util/csv.h]: It was based on `strtok` once, not sure if it still does.

Comment (Tomatower) [inline libopenage/util/csv.h]: Ah now I see what you mean... It is finally consumed [here](https://github.com/SFTtech/openage/blob/master/libopenage/util/strings.cpp#L90) - and there write access is required - which is still not completely broken - if the string is not modified in length one can use ```&line[0]````- and continue to avoid any copy

**Comment by jonaspm** [comment]
Hello everyone, I am liking this project but... why use docx instead of a more documented and libre option as .odt?

thanks in advance.

**Comment by elnabo** [comment]
If I remember correctly the .docx files are in fact csv files.

**Comment by ChipmunkV** [comment]
@jamesmcm, in other words: it's not *that* docx.

**Comment by TheJJ** [comment]
This file suffix is purely a troll, in fact the files are just plain text. We wanted to use them as as "temporary solution" until we have [nyan](https://github.com/SFTtech/nyan), but this turned out to be way more complicated, so we still have them as of today, but they _will_ go away at least after my master thesis about nyan. :stuck_out_tongue:

**Comment by TheJJ** [comment]
I'm finally done here. Massive overhaul n stuff, let's see how it works out. Please test and break it, especially the path system.

File: openage/convert/game_versions.py [hunk 5]
```diff
@@ -19,32 +19,45 @@ class GameVersion(enum.Enum):
...
-        "African Kingdoms",
+    age2_hd_ak = (
+        "AOE2 HD African Kingdoms",
         True,
         {'AoK HD.exe', 'resources/_common/dat/empires2_x2_p1.dat',
          'resources/_packages/african-kingdoms/config.json'},
     )
+    # HD Edition v5.1+ with Rise of Rayas
+    age2_hd_rayas = (
+        "AOE2 HD Rise of Rayas (Version 5.x)",
```
Comment (goto-bus-stop) [inline openage/convert/game_versions.py]: Nit: s/Rayas/Rajas

**Comment by goto-bus-stop** [comment]
Convert stuff looks correct to me so far, I'll try a few versions in a minute.

**Comment by TheJJ** [comment]
Hm damn I'm encountering some issues when I do:
```
./configure --mode=debug --prefix=/usr/games --raw-cmake-args -DPYTHON=/usr/bin/python3.6
make install DESTDIR=/tmp/oatest
LD_LIBRARY_PATH=/tmp/oatest/usr/games/lib64/ PYTHONPATH=/tmp/oatest/usr/lib64/python3.6/site-packages python3.6 ./openage game --asset-dir /tmp/oatest/usr/games/share/openage/
```

Then the global asset path isn't resolved correctly. Should not be hard to fix, let's see...

File: openage/__main__.py [hunk 6]
```diff
@@ -103,10 +102,17 @@ def main(argv=None):
...
+    try:
+        from . import config
+
+        if args.no_devmode:
+            config.DEVMODE = False
+        if args.devmode:
+            config.DEVMODE = True
+    except ImportError:
+        if args.no_devmode or args.devmode:
+            print("code was not yet generated, "
```
Comment (elnabo) [inline openage/__main__.py]: This line looks weird, shouldn't the comma be out of the first string ?

Comment (TheJJ) [inline openage/__main__.py]: dunno, how'd you write it? :)

**Comment by TheJJ** [comment]
I think it works now. Packagers, please test if this branch is packageable and works when installed. It should generate assets then and everything just work as you would think it should.

File: openage/__main__.py (hunk 6 above)
Comment (elnabo) [inline openage/__main__.py]: Well why not just ` print("code was not yet generated, ignoring devmode activation request")`
It should still be under the 100 char limit.

Comment (TheJJ) [inline openage/__main__.py]: Mainly because my editor window is not that wide, it ends at ~75 somewhere, so I try to break lines visually. It's 84 now, I changed it.

Comment (elnabo) [inline openage/__main__.py]: I didn't knew this syntax existed for string concatenation existed in python, still stuck in 2.7.

Comment (TheJJ) [inline openage/__main__.py]: It's like the compiletime string constant concat in C, very handy.
