### PR TITLE
change default entry sector value from null

### LINKED ISSUE #1730: error: cannot initialize a member subobject of type 'sector_id_t' (aka 'unsigned long') with an rvalue of type 'std::nullptr_t'
Hi,
I compiled the last tag 0.6.0 and build failed on FreeBSD 14.2.

FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)
Target: x86_64-unknown-freebsd14.2
Thread model: posix
InstalledDir: /usr/bin

```
FAILED: libopenage/CMakeFiles/libopenage.dir/pathfinding/pathfinder.cpp.o 
/usr/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QMLBUILTINS_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -Dlibopenage_EXPORTS -I/usr/ports/games/openage/work/.build/libopenage/libopenage_autogen/include -I/usr/ports/games/openage/work/.build/libopenage -I/usr/ports/games/openage/work/openage-0.6.0/libopenage -I/usr/local/include/freetype2 -I/usr/local/include/opus -I/usr/ports/games/openage/work/.build/libopenage/coord -isystem /usr/local/include -isystem /usr/local/include/eigen3 -isystem /usr/local/include/qt6/QtCore -isystem /usr/local/include/qt6 -isystem /usr/local/lib/qt6/mkspecs/freebsd-clang -isystem /usr/local/include/qt6/QtQuick -isystem /usr/local/include/qt6/QtGui -isystem /usr/local/include/qt6/QtQml -isystem /usr/local/include/qt6/QtQmlIntegration -isystem /usr/local/include/qt6/QtQmlBuiltins -isystem /usr/local/include/qt6/QtNetwork -isystem /usr/local/include/qt6/QtQmlModels -isystem /usr/local/include/qt6/QtOpenGL -isystem /usr/local/include/qt6/QtMultimedia -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -DNDEBUG -O3 -std=gnu++20 -fPIC  -Wall -Wextra -pedantic -Wno-gnu-statement-expression -pthread -fPIC -MD -MT libopenage/CMakeFiles/libopenage.dir/pathfinding/pathfinder.cpp.o -MF libopenage/CMakeFiles/libopenage.dir/pathfinding/pathfinder.cpp.o.d -o libopenage/CMakeFiles/libopenage.dir/pathfinding/pathfinder.cpp.o -c /usr/ports/games/openage/work/openage-0.6.0/libopenage/pathfinding/pathfinder.cpp
/usr/ports/games/openage/work/openage-0.6.0/libopenage/pathfinding/pathfinder.cpp:473:15: error: cannot initialize a member subobject of type 'sector_id_t' (aka 'unsigned long') with an rvalue of type 'std::nullptr_t'
  473 |         entry_sector{nullptr},
      |                      ^~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

```

### PR DESCRIPTION
**Pull request by jere8184**
closes #1730

### CODE REVIEW

**Comment by jere8184** [comment]
> You should not assign 0 or any valid portal ID. If you need to have this value uninitialized at the start, use `std::optional`.
There's not necessarily a need for it to be uninitialized. The algorithm works fine no matter the value it starts with, which is why there's also no reason for it to be initialized in the first place; any initial value you choose is meaningless.

File: libopenage/pathfinding/pathfinder.cpp [hunk 1]
```diff
@@ -269,11 +269,11 @@ const Pathfinder::portal_star_t Pathfinder::portal_a_star(const PathRequest &req
 		}
 
 		// get the exits of the current node
-		const auto &exits = current_node->get_exits(current_node->entry_sector);
+		const auto &exits = current_node->get_exits(current_node->entry_sector.value());
```
Comment (heinezen) [inline libopenage/pathfinding/pathfinder.cpp:272]:
```suggestion
		ENSURE(current_node->entry_sector != std::nullopt, "Entry sector not set for portal node.");
		const auto &exits = current_node->get_exits(*current_node->entry_sector);
```

Doing it like this will check if the value of the optional was correctly set, but only in debug mode because the openage `ENSURE` macro only gets included in debug builds (like an assert). You don't need to add it here, I just wanted to mention it :)

File: libopenage/pathfinding/pathfinder.h [hunk 2]
```diff
@@ -5,6 +5,7 @@
 #include <map>
 #include <memory>
 #include <unordered_map>
+#include <optional>
```
Comment (heinezen) [inline libopenage/pathfinding/pathfinder.h:8]: The imports are not correctly ordered (o comes before u)

File: libopenage/pathfinding/pathfinder.cpp (hunk 1 above)
Comment (jere8184) [reply libopenage/pathfinding/pathfinder.cpp:273]: Thanks for the advice, i've added it.

**Review by heinezen — APPROVED** [review]
Very good!
